import { Dimensions, StyleSheet } from 'react-native'

export default StyleSheet.create({
	container: {
		flex: 1,
	},
	banner: {
		width: Dimensions.get('window').width,
		position: 'absolute',
		top: 0,
		left: 0,
		right: 0,
		height: 200,
		zIndex: 0,
	},
	backgroundGradient: {
		position: 'absolute',
		left: 0,
		right: 0,
		top: 0,
		height: '100%',
	},
	pageContainer: {
		paddingTop: 36,
		paddingHorizontal: 16,
		gap: 0,
	},
	userInfoContainer: {
		paddingTop: 15,
		paddingRight: 2,
		display: 'flex',
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
	},
	userName: {
		fontFamily: 'Ubuntu_700',
		fontSize: 20,
		fontWeight: '700',
		lineHeight: 24,
		textAlign: 'left',
		color: '#fff',
	},
	iconsSection: {
		display: 'flex',
		flexDirection: 'row',
		gap: 16,
		flex: 1,
		justifyContent: 'flex-end'
	},
	balanceSection: {
		marginTop: 24,
		backgroundColor: '#fff',
		borderTopRightRadius: 32,
		borderBottomRightRadius: 8,
		borderTopLeftRadius: 8,
		borderBottomLeftRadius: 32,
		padding: 24,
		shadowColor: '#000',
		shadowOffset: {
			width: 0,
			height: 5,
		},
		shadowOpacity: 0.34,
		shadowRadius: 6.27,
		elevation: 10,
	},
	balanceTitleContainer: {
		display: 'flex',
		flexDirection: 'row',
		justifyContent: 'space-between',
	},
	balanceTitle: {
		fontFamily: 'Ubuntu',
		fontSize: 20,
		fontWeight: '400',
		lineHeight: 22.98,
		textAlign: 'left',
		color: 'rgba(25, 25, 25, 0.6)',
	},
	balanceValue: {
		fontFamily: 'Ubuntu_700',
		fontSize: 24,
		fontWeight: '700',
		lineHeight: 27.58,
		textAlign: 'left',
		marginTop: 8,
	},
	balanceValueConverted: {
		fontFamily: 'Ubuntu',
		fontSize: 14,
		fontWeight: '500',
		lineHeight: 16.09,
		textAlign: 'left',
		color: 'rgba(25, 25, 25, 0.6)',
	},
	accessStatementButton: {
		height: 26,
		paddingTop: 6,
		paddingBottom: 6,
		paddingRight: 8,
		paddingLeft: 8,
		borderRadius: 8,
		backgroundColor: '#191919',
	},
	accessStatementButtonText: {
		fontFamily: 'Ubuntu_700',
		fontSize: 12,
		fontWeight: '700',
		lineHeight: 13.79,
		textAlign: 'left',
		color: '#fff',
	},
	cardBalanceSection: {
		marginTop: 24,
		backgroundColor: '#fff',
		borderTopRightRadius: 32,
		borderBottomRightRadius: 8,
		borderTopLeftRadius: 8,
		borderBottomLeftRadius: 32,
		padding: 24,
		shadowColor: '#000',
		shadowOffset: {
			width: 0,
			height: 5,
		},
		shadowOpacity: 0.34,
		shadowRadius: 6.27,
		elevation: 10,
		display: 'flex',
		justifyContent: 'space-between',
	},
	containerSectionCard: {
		flexDirection: 'row',
	},
	cardContainerSection: {
		flexDirection: 'row'
	},
	cardBalanceBackgroundGradient: {
		position: 'absolute',
		left: 0,
		right: 0,
		top: 0,
		bottom: 0,
		borderTopRightRadius: 32,
		borderBottomRightRadius: 8,
		borderTopLeftRadius: 8,
		borderBottomLeftRadius: 32,
	},
	cardBalanceTitle: {
		fontFamily: 'Ubuntu',
		fontSize: 20,
		fontWeight: '400',
		lineHeight: 22.98,
		textAlign: 'left',
		color: '#191919',
	},
	cardBalanceActiveTitle: {
		fontFamily: 'Ubuntu',
		fontSize: 20,
		fontWeight: '400',
		lineHeight: 22.98,
		textAlign: 'left',
		color: '#191919',
		flex: 2,
		paddingTop: 26,
		paddingLeft: 0
	},
	cardBalanceValue: {
		fontFamily: 'Ubuntu_700',
		fontSize: 24,
		fontWeight: '700',
		lineHeight: 27.58,
		textAlign: 'left',
		marginTop: 8,
	},
	cardBalanceValueConverted: {
		fontFamily: 'Ubuntu',
		fontSize: 14,
		fontWeight: '500',
		lineHeight: 16.09,
		textAlign: 'left',
		color: 'rgba(25, 25, 25, 0.6)',
		marginTop: 8,
	},
	accessTravelCardButton: {
		height: 26,
		paddingTop: 6,
		paddingBottom: 6,
		paddingRight: 8,
		paddingLeft: 8,
		borderRadius: 8,
		backgroundColor: '#fff',
		marginTop: 16,
	},
	activateTravelCardButton: {
		height: 46,
		paddingTop: 6,
		paddingBottom: 6,
		paddingRight: 8,
		paddingLeft: 8,
		borderRadius: 30,
		backgroundColor: '#000',
		marginTop: 16,
	},
	accessTravelCardButtonText: {
		fontFamily: 'Ubuntu_700',
		fontSize: 12,
		fontWeight: '700',
		lineHeight: 13.79,
		textAlign: 'center',
		color: '#191919',
	},
	conciergeSection: {
		marginTop: 24,
		backgroundColor: '#fff',
		borderTopRightRadius: 32,
		borderBottomRightRadius: 8,
		borderTopLeftRadius: 8,
		borderBottomLeftRadius: 32,
		padding: 24,
		shadowColor: '#000',
		shadowOffset: {
			width: 0,
			height: 5,
		},
		shadowOpacity: 0.34,
		shadowRadius: 6.27,
		elevation: 10,
		display: 'flex',
		flexDirection: 'row',
		justifyContent: 'space-between',
	},
	conciergeBackgroundGradient: {
		position: 'absolute',
		left: 0,
		right: 0,
		top: 0,
		bottom: 0,
		borderTopRightRadius: 32,
		borderBottomRightRadius: 8,
		borderTopLeftRadius: 8,
		borderBottomLeftRadius: 32,
	},
	conciergeTitle: {
		fontFamily: 'Ubuntu_700',
		fontSize: 16,
		fontWeight: '700',
		lineHeight: 18.38,
		textAlign: 'left',
		color: '#191919',
	},
	conciergeSubTitle: {
		fontFamily: 'Ubuntu',
		fontSize: 12,
		fontWeight: '400',
		lineHeight: 18,
		textAlign: 'left',
		marginTop: 8,
		maxWidth: 200,
	},
	conciergeButton: {
		height: 26,
		paddingTop: 6,
		paddingBottom: 6,
		paddingRight: 8,
		paddingLeft: 8,
		borderRadius: 8,
		backgroundColor: '#fff',
		marginTop: 16,
	},
	conciergeButtonText: {
		fontFamily: 'Ubuntu_700',
		fontSize: 12,
		fontWeight: '700',
		lineHeight: 13.79,
		textAlign: 'center',
		color: '#191919',
	},
	cashbackCardContainer: {
		gap: 24,
		overflow: 'visible'
	},
	spacer: {
		minHeight: 110,
	},
	supportCardsContainer: {
		gap: 24,
		overflow: 'visible',
		marginTop: 16,
	},
	supportCard: {
		backgroundColor: '#000',
		borderTopRightRadius: 32,
		borderBottomRightRadius: 8,
		borderTopLeftRadius: 8,
		borderBottomLeftRadius: 32,
		padding: 24,
		shadowColor: '#000000',
		shadowOffset: {
			width: 4,
			height: 4,
		},
		shadowOpacity: 0.29,
		shadowRadius: 4.65,
		elevation: 7,
		justifyContent: 'center',
		alignItems: 'center',
		height: 248,
		width: 258
	},
	supportCardTitle: {
		color: '#fff',
		fontSize: 16,
		lineHeight: 18,
	},
	firstDepositCard: {
		padding: 24,
		marginTop: 24,
		backgroundColor: '#E30974',
	},
	firstDepositCardImage: {
		gap: 16,
	},
	firstDepositCardText: {
		color: '#fff',
		fontSize: 20,
		lineHeight: 22,
		maxWidth: 240
	},
	firstDepositCardButton: {}
})
