import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
	contentContainer: {
		paddingHorizontal: 24,
		paddingVertical: 56,
		flex: 1,
		backgroundColor: '#fff',
		overflow: 'visible',
	},
	cashbackCardContainer: {
		gap: 24,
		overflow: 'visible',
	},
	curvedCardTextContainer: {
		maxWidth: '60%',
	},
	curvedCard: {
		flexDirection: 'row',
		paddingHorizontal: 24,
		paddingVertical: 12,
		justifyContent: 'space-between',
		alignItems: 'center',
		marginVertical: 16,
	},
	curvedCardTitle: {
		fontSize: 16,
		lineHeight: 18,
	},
	curvedCardSubtitle: {
		fontSize: 12,
		lineHeight: 18,
		marginTop: 8,
		marginBottom: 8,
	},
	cardTravelCardBackgroundGradient: {
		position: 'absolute',
		left: 0,
		right: 0,
		top: 0,
		bottom: 0,
		borderTopRightRadius: 32,
		borderBottomRightRadius: 8,
		borderTopLeftRadius: 8,
		borderBottomLeftRadius: 32,
	},
	conciergeBackgroundGradient: {
		position: 'absolute',
		left: 0,
		right: 0,
		top: 0,
		bottom: 0,
		borderTopRightRadius: 32,
		borderBottomRightRadius: 8,
		borderTopLeftRadius: 8,
		borderBottomLeftRadius: 32,
	},
	spacer: {
		minHeight: 130,
	},
	conciergeButton: {
		height: 26,
		paddingTop: 6,
		paddingBottom: 6,
		paddingRight: 8,
		paddingLeft: 8,
		borderRadius: 8,
		backgroundColor: '#fff',
		marginTop: 16,
	},	
	conciergeTitle: {
		fontFamily: 'Ubuntu_700',
		fontSize: 16,
		fontWeight: '700',
		lineHeight: 18.38,
		textAlign: 'left',
		color: '#191919',
	},
	conciergeSubTitle: {
		fontFamily: 'Ubuntu',
		fontSize: 12,
		fontWeight: '400',
		lineHeight: 18,
		textAlign: 'left',
		marginTop: 8,
		maxWidth: 200
	},
	conciergeSection: {
		marginTop: 24,
		backgroundColor: '#fff',
		borderTopRightRadius: 32,
		borderBottomRightRadius: 8,
		borderTopLeftRadius: 8,
		borderBottomLeftRadius: 32,
		padding: 24,
		shadowColor: '#000',
		shadowOffset: {
			width: 0,
			height: 5,
		},
		shadowOpacity: 0.34,
		shadowRadius: 6.27,
		elevation: 10,
		display: 'flex',
		flexDirection: 'row',
		justifyContent: 'space-between',
	},
	subText: {
		fontSize: 16,
		lineHeight: 24,
		color: '#707A81',
		marginBottom: 8,
		alignSelf: 'center',
		paddingTop: 24
	},
})
